# deploy site image to ecs
name: deploy docker image
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: check out repo
        uses: actions/checkout@v3
      - name: build image and push it to ghcr.io
        run: |
          echo "${{ secrets.PACKAGE_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build . -t ghcr.io/debonex/debonex-site:latest
          docker push ghcr.io/debonex/debonex-site:latest
      - name: deploy image to ecs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          password: ${{ secrets.ECS_PASSWORD }}
          script: |
            echo "${{ secrets.PACKAGE_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker stop site
            docker rmi ghcr.io/debonex/debonex-site:latest
            docker pull ghcr.io/debonex/debonex-site:latest
            docker run -d --rm --name site -p 3000:3000 -v ${{ secrets.ECS_DATABASE_PATH }}:/app/site.db --env PASSWORD=${{ secrets.SITE_PASSWORD }} ghcr.io/debonex/debonex-site:latest
